services:
  - type: web
    name: telegram-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    envVars:
      - key: BOT_TOKEN
        value: "توکن_ربات_تو_اینجا"
      - key: WEBHOOK_URL
        value: "https://yourproject.onrender.com"  # آدرس پروژه‌ات روی Render
