services:
  - type: web
    name: appleid035
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        value: 8255151341:AAGFwWdSGnkoEVrTOej0jaNUco-DmgKlbCs
